<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

1. Compute the scaler product of two vectors

> In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number. 

> we can calculate it this way:

        a · b = ax × bx + ay × by
        
Hint: [Dot Product](https://www.mathsisfun.com/algebra/vectors-dot-product.html)

In [2]:
import numpy as np

In [3]:
a = [-12, 16]
b = [12, 9]

In [4]:
#ANS to 1
print(np.dot(a,b))

0


2. Compute the cross product of two vectors

> When a and b start at the origin point (0,0,0), the Cross Product will end at:

        cx = aybz − azby
        cy = azbx − axbz
        cz = axby − aybx
        
Hint: [Cross Product](https://www.mathsisfun.com/algebra/vectors-cross-product.html)

In [5]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,5,6], [1,2,3]])

In [6]:
#ANS to 2
print(np.cross(x,y))

[[-3  6 -3]
 [ 3 -6  3]]


3. Compute the Hademard product (entry-wise multiplication) of two vectors.

> In mathematics, the Hadamard product (also known as the Schur product[1] or the entrywise product[2]:ch. 5) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element i, j is the product of elements i, j of the original two matrices. It should not be confused with the more common matrix product. It is attributed to, and named after, either French mathematician Jacques Hadamard or German mathematician Issai Schur. [Wiki](https://en.wikipedia.org/wiki/Hadamard_product_(matrices))

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/4eb9bb54b2820fb3583901ec05bc4b474b6d90bc)

In [8]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [9]:
#ANS to 3
print(np.multiply(a,b))

[[ 5 12]
 [21 32]]


4. Compute the sum of two matrices.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/0fb7845af355c550d44020e52699069c044126a9)

In [12]:
# Program to add two matrices using nested loop

X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

In [21]:
#ANS to 4
for i in range(len(X)):
    #print (f"i is now {i}")
    #print(f"X[{i}] is {X[i]}")
    #print(f"Y[{i}] is {Y[i]}")
    for j in range(len(X[i])):
        #print (f"j is now {j}")
        #print(f"X[{i}][{j}] is {X[i][j]}")
        #print(f"Y[{i}][{j}] is {Y[i][j]}")
        result[i][j] = X[i][j] + Y[i][j]
print (result)

[[17, 15, 4], [10, 12, 9], [11, 13, 18]]


5. Compute the product of two matrices.

![](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg)

In [82]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

In [68]:
#ANS to 5 (with output of code iterations to help visualization)
for i in range(len(X)):
    print (f"i is now {i}")
    for j in range(len(Y[0])):
        print (f"\tj is now {j}")
        for k in range(len(Y)):
            print (f"\t\tk is now {k}")
            print(f"\t\t\tX[{i}][{k}] is {X[i][k]}")
            print(f"\t\t\tY[{k}][{j}] is {Y[k][j]}")
            print(f"\t\t\tresult[{i}][{j}] was {result[i][j]}")
            result[i][j] += X[i][k] * Y[k][j]
            print(f"\t\t\tresult[{i}][{j}] is now {result[i][j]}")
print(result)

i is now 0
	j is now 0
		k is now 0
			X[0][0] is 12
			Y[0][0] is 5
			result[0][0] was 0
			result[0][0] is now 60
		k is now 1
			X[0][1] is 7
			Y[1][0] is 6
			result[0][0] was 60
			result[0][0] is now 102
		k is now 2
			X[0][2] is 3
			Y[2][0] is 4
			result[0][0] was 102
			result[0][0] is now 114
	j is now 1
		k is now 0
			X[0][0] is 12
			Y[0][1] is 8
			result[0][1] was 0
			result[0][1] is now 96
		k is now 1
			X[0][1] is 7
			Y[1][1] is 7
			result[0][1] was 96
			result[0][1] is now 145
		k is now 2
			X[0][2] is 3
			Y[2][1] is 5
			result[0][1] was 145
			result[0][1] is now 160
	j is now 2
		k is now 0
			X[0][0] is 12
			Y[0][2] is 1
			result[0][2] was 0
			result[0][2] is now 12
		k is now 1
			X[0][1] is 7
			Y[1][2] is 3
			result[0][2] was 12
			result[0][2] is now 33
		k is now 2
			X[0][2] is 3
			Y[2][2] is 9
			result[0][2] was 33
			result[0][2] is now 60
	j is now 3
		k is now 0
			X[0][0] is 12
			Y[0][3] is 2
			result[0][3] was 0
			result[0][3] is no

In [56]:
#ANS to 5
for i in range(len(X)):
    for j in range(len(Y[0])):
        for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j]
            
print(result)

[[114, 160, 60, 27], [74, 97, 73, 14], [119, 157, 112, 23]]


In [79]:
# DO NOT RUN: proof of concept for error-checking in matrix_multiply procedure
X = np.random.randint(100,size=(3,3))
Y = np.random.randint(100,size=(2,4))
print(X)
print(Y)

[[ 2 18 68]
 [ 1 50 88]
 [33 92 14]]
[[45 74 99  7]
 [39 93 61 15]
 [ 4  0 47  3]]


In [84]:
#ANS to 5 generalised to a procedure taking any two matrices

def matrix_multiply (a,b):
    # check that length of columns in Matrix a is same as length as rows in Matrix b
    if len(a[0]) != len(b):
        print("Invalid operation: Number of columns for first matrix must equal number of rows for second matrix")
    else:
    # initialize resultant matrix with shape (rows of matrix a, columns of matrix b)
        result = [ [0 for i in range(len(b[0]))] for j in range(len(a)) ]
        # print(f'Initialized result matrix: {result}')
    # iterate thru rows of matrix a
        for i in range(len(a)):
            # iterate thru columns of matrix b
            for j in range(len(b[0])):
                # iterate thru rows of matrix b
                for k in range(len(b)):
                    result[i][j] += a[i][k] * b[k][j]
        return result
    
print(f'The multiplication of Matrix X by Matrix Y is: {matrix_multiply(X,Y)}')

The multiplication of Matrix X by Matrix Y is: [[114, 160, 60, 27], [74, 97, 73, 14], [119, 157, 112, 23]]


In [85]:
#ANS to 5 generalised to a procedure taking any two matrices, but using list comprehensions in lieu of nested for-loops
def matrix_multiply (a,b):
    return [ [sum(i*j for i,j in zip(r,c)) for c in zip(*b)] for r in a ]

print(f'The multiplication of Matrix X by Matrix Y is: {matrix_multiply(X,Y)}')

The multiplication of Matrix X by Matrix Y is: [[114, 160, 60, 27], [74, 97, 73, 14], [119, 157, 112, 23]]


In [92]:
# DO-NOT-RUN - Decomposing nested list comprehension for visualization of expression 'for i,j in zip (r,c)'
r = [12,7,3]
c = [5,6,4]
e = zip(r,c)
print(list(e))

[(12, 5), (7, 6), (3, 4)]


In [90]:
# DO-NOT-RUN - decomposition of list comprehension for visualization of 'zip(*b)'

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

d = zip(*Y)
print(list(d))

for c in d: print(c)

[(5, 6, 4), (8, 7, 5), (1, 3, 9), (2, 0, 1)]


6. Compute the determinant of an n x n matrix.

![](https://integratedmlai.com/wp-content/uploads/2018/12/Matrix_Det_2x2.png)

Hint: [Find the Determinant of a Matrix with Pure Python without Numpy or Scipy](https://integratedmlai.com/find-the-determinant-of-a-matrix-with-pure-python-without-numpy-or-scipy/)

Hint: Use 
> np.linalg.det

In [93]:
matrix = [[-2,2,-3],[-1,1,3],[2,0,-1]]

In [94]:
determinant = np.linalg.det(matrix)
print(determinant)

17.999999999999996


7. Compute the inverse of an n x n matrix.

For a 3×3 matrix

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation3.gif)

the matrix inverse is

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation4.gif)

Hint: Use 
> from numpy.linalg import inv

In [95]:
a = np.array([[1., 2.], [3., 4.]])

In [96]:
a_inverse = np.linalg.inv(a)
print(a_inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]




---



---



> > > > > > > > > © 2019 Institute of Data


---



---



